### PR TITLE
[Docs] Grammar fixes

### PR DESCRIPTION
**Pull request by rowild**
Just some minor grammar fixes for the top-level files "Readme", "From Scratch", and "Getting Started".

### CODE REVIEW

**Comment by mercs600** [comment]
@rowild great work, thank you. Could you squash your commits and run commitlint task for your commits messages ?

**Comment by rowild** [comment]
@mercs600 I would love to, but I have no idea how to do that nor what it actually is. Would you mind to give me some instructions, please?

**Comment by mercs600** [comment]
I did squash and change commit message for you. 
We use https://www.conventionalcommits.org/en/v1.0.0/. 
You need to to install all npm modules in this project, then when you run git commit -m "your message" husky script will run commitlint for you. You can also use yarn commitlint to check your message

**Comment by rowild** [comment]
@mercs600 Thank you! But that means I have to checkout the repo to my desktop. Forking and branching on my fork will not suffice, right?

**Comment by mercs600** [comment]
that's right, please clone it locally and install all npm modules.

**Pull request merged**
